Fixed test-publish action and added the release action

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,9 +1,9 @@
-name: Publish Python Package to Test PyPI
+name: Publish Python Package to PyPI
 
 on:
   push:
     tags:
-      - 'v*-test'
+      - 'v*'
 
 
 permissions:
@@ -15,6 +15,14 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
+    - name: Check if tag ends with "-test"
+    
+      run: |
+        if [[ "${{ github.ref }}" == *-test ]]; then
+        echo "Tag ends with '-test'. This cannot be released to PyPi, check the test-PyPi action. Terminating job."
+        exit 1
+        fi
+      shell: bash
 
     - name: Checkout code
       uses: actions/checkout@v3
@@ -53,10 +61,10 @@ jobs:
     - name: Publish to TestPyPI
       if: startsWith(github.ref, 'refs/tags/v')
       run: |
-        python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
+        python -m twine upload dist/*
       env:
         TWINE_USERNAME: __token__
-        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
+        TWINE_PASSWORD: ${{ secrets.RELEASE_PYPI_TOKEN }}
       
         #env:
       #  name: testpypi
